### PR TITLE
CloudWatchLogsAddon: setting logRetentionDays param does not work and not set cloudWatchLogs.logRetentionDays when creating CloudWatch Log Groups

### LINKED ISSUE #888: CloudWatchLogsAddon: setting logRetentionDays param does not work and not set cloudWatchLogs.logRetentionDays when creating CloudWatch Log Groups
### Describe the bug

When adding `CloudWatchLogsAddon` and setting parm `logRetentionDays` does not work. When respective CloudWatch LogGroups are created no retention is set a.k.a all log groups are set with `never expire`.

```typescript
const addOn = new blueprints.addons.CloudWatchLogsAddon({
  namespace: 'aws-for-fluent-bit',
  createNamespace: true,
  serviceAccountName: 'aws-fluent-bit-for-cw-sa',
  logGroupPrefix: '/aws/eks/<your-cluster-name>',
  logRetentionDays: 90 
});
```

### Expected Behavior

When adding `CloudWatchLogsAddon` and setting parm `logRetentionDays`  when respective CloudWatch LogGroups are created retention for all log groups must be set to expire in number of days specified in param `logRetentionDays`.

### Current Behavior

When adding `CloudWatchLogsAddon` and setting parm `logRetentionDays` does not work. When respective CloudWatch LogGroups are created no retention is set a.k.a all log groups are set with `never expire`.

```typescript
const addOn = new blueprints.addons.CloudWatchLogsAddon({
  namespace: 'aws-for-fluent-bit',
  createNamespace: true,
  serviceAccountName: 'aws-fluent-bit-for-cw-sa',
  logGroupPrefix: '/aws/eks/<your-cluster-name>',
  logRetentionDays: 90 
});
```

There are 2 problems why this is happening:

1. Lack of persimmons which allow `logs:PutRetentionPolicy` and `logs:DeleteRetentionPolicy` 
in this file [https://github.com/aws-quickstart/cdk-eks-blueprints/blob/69d730e538be47189a63e92bf5799e51c1792ae2/lib/addons/cloudwatch-logs/iam-policy.ts#L7](https://github.com/aws-quickstart/cdk-eks-blueprints/blob/69d730e538be47189a63e92bf5799e51c1792ae2/lib/addons/cloudwatch-logs/iam-policy.ts#L7)

2. in addon code `CloudWatchLogsAddon` we set wrong param `cloudWatchLogs.log_retention_days` check here [https://github.com/aws/eks-charts/blob/2ca1cb467a7ded4a608ab314b5cecf04dc7d758c/stable/aws-for-fluent-bit/templates/configmap.yaml#L140C42-L140C73](https://github.com/aws/eks-charts/blob/2ca1cb467a7ded4a608ab314b5cecf04dc7d758c/stable/aws-for-fluent-bit/templates/configmap.yaml#L140C42-L140C73) it should be `cloudWatchLogs.logRetentionDays`

### Reproduction Steps

Just try to execute code from example page [https://aws-quickstart.github.io/cdk-eks-blueprints/addons/cloudwatch-logs/](https://aws-quickstart.github.io/cdk-eks-blueprints/addons/cloudwatch-logs/)

### Possible Solution

I will provide PR with needed changes to fix this 

### Additional Information/Context

_No response_

### CDK CLI Version

2.99.1 (build b2a895e)

### EKS Blueprints Version

1.12.0

### Node.js Version

v18.15.0

### Environment details (OS name and version, etc.)

Mac OS Ventura - Version 13.6.2

### Other information

_No response_

### PR DESCRIPTION
**Pull request by bnaydenov**
fix #888

### CODE REVIEW

**Review by elamaran11 — APPROVED** [review]
LGTM

**Comment by elamaran11** [comment]
@shapirov103 Please run e2e and merge.

File: lib/addons/cloudwatch-logs/index.ts [hunk 1]
```diff
@@ -109,6 +109,6 @@ function populateValues(clusterInfo: ClusterInfo, helmOptions: CloudWatchLogsAdd
     setPath(values, "cloudWatchLogs.logGroupTemplate", `${helmOptions.logGroupPrefix}/$kubernetes['namespace_name']`);
     setPath(values, "cloudWatchLogs.logStreamTemplate", "$kubernetes['container_name'].$kubernetes['pod_name']");
     setPath(values, "cloudWatchLogs.log_key", "log");
```
Comment (shapirov103) [inline lib/addons/cloudwatch-logs/index.ts:111]: since we are fixing the chart values, do you mind also fixing log_key here which is also incorrectly using snake case - mustbe `logKey` based on https://github.com/aws/eks-charts/blob/master/stable/aws-for-fluent-bit/values.yaml.

**Review by shapirov103 — COMMENTED** [review]
@bnaydenov please see my comment, and thank you for this fix.

File: lib/addons/cloudwatch-logs/index.ts (hunk 1 above)
Comment (bnaydenov) [reply lib/addons/cloudwatch-logs/index.ts:111]: Ok, make sense, fixed in my last commit

**Review by shapirov103 — APPROVED** [review]
LGTM
